import os
import json
from typing import Dict, Any, List
from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from agent.base_agent import BaseAgent
from agent.state import AgentState
from agent.RAGAgent import RAGAgent
from agent.planner import GraphPlanner

class CoordinatorAgent(BaseAgent):
    def __init__(self, use_kg_planner: bool = True):
        super().__init__(agent_name="CoordinatorAgent")
        self.llm = self.model
        self.rag = RAGAgent()
        self.use_kg_planner = use_kg_planner
        self.planner = GraphPlanner() if use_kg_planner else None

    def run(self, state: AgentState) -> Dict[str, Any]:
        """
        Orchestrates the workflow using KG-driven planning (Ours) or LLM-only (Baseline).
        """
        print(f"[{self.agent_name}] Retrieving context and planning workflow... (KG={self.use_kg_planner})")
        
        user_input = state.get("user_input", "")
        intent = state.get("intent", "")
        task_params = state.get("task_params", {})
        
        # Enforce default molecule count if not specified
        if "num_molecules" not in task_params:
            task_params["num_molecules"] = 20
            
        # --- PLANNING STRATEGY ---
        current_resources = set()
        # Map task_params to KG resources
        if "pdb_id" in task_params or "target_name" in task_params:
            current_resources.add("Target_ID")
        if "smiles" in task_params or "molecules" in task_params:
            current_resources.add("Molecules_SMILES") 

        print(f"[{self.agent_name}] Current Resources: {current_resources}")

        plan = []
        reasoning = ""

        if self.use_kg_planner:
            # --- KG-DRIVEN PLANNING (OURS) ---
            try:
                plan = self.planner.generate_plan(intent, current_resources, task_params)
                reasoning = f"Plan generated by KG Backward Chaining for intent '{intent}'."
            except Exception as e:
                print(f"[{self.agent_name}] KG Planning failed: {e}")
                plan = []
                reasoning = f"Planning failed: {e}"
        else:
            # --- BASELINE (LLM-ONLY) ---
            # Simulate a standard ReAct agent that guesses the plan based on tool descriptions
            # It lacks the global dependency graph.
            prompt = f"""
            You are a Coordinator Agent. 
            User Intent: {intent}
            Available Agents: TargetAgent, GeneratorAgent, EvaluatorAgent, SynthesisAgent, ReportAgent.
            
            Decide the sequence of agents to run.
            Return ONLY a JSON list of agent names, e.g. ["Agent1", "Agent2"].
            """
            try:
                # In a real baseline, we'd call the LLM. 
                from langchain_core.messages import SystemMessage
                resp = self.model.invoke([SystemMessage(content=prompt)])
                import re
                match = re.search(r'\[.*\]', resp.content, re.DOTALL)
                if match:
                    plan = json.loads(match.group(0))
                else:
                    plan = []
                reasoning = "Plan generated by LLM (Baseline) without KG."
            except Exception as e:
                reasoning = f"Baseline planning failed: {e}"
                plan = []

        # 3. Post-Processing (Report Agent)
        # ReportAgent is usually an implicit requirement for any user-facing task,
        # but technically it depends on "Evaluation_Report" or "Synthesis_Plan".
        # Our planner might have included it if we mapped intent -> Final_Report.
        # But let's ensure it's there if not forbidden.
        
        restrictions_value = task_params.get("restrictions", [])
        if isinstance(restrictions_value, str):
            restrictions_list = [restrictions_value]
        elif isinstance(restrictions_value, list):
            restrictions_list = restrictions_value
        else:
            restrictions_list = []

        allow_report = "No PDF report" not in restrictions_list and "No ReportAgent" not in restrictions_list
        
        if allow_report and plan and plan[-1] != "ReportAgent":
            plan.append("ReportAgent")
        elif not allow_report and "ReportAgent" in plan:
            plan.remove("ReportAgent")

        # 4. Handle "The Trap Task" (Logic Validation)
        # If intent is "synthesis_planning" (Target: 5HT1B) but NO molecules provided:
        # - Baseline (LLM) might try to run SynthesisAgent directly.
        # - Ours (GraphPlanner) will see: Need Synthesis -> Need Molecules -> Need Generator -> Need Target.
        # - So Plan will be: [TargetAgent, GeneratorAgent, SynthesisAgent, ReportAgent]
        
        if not plan:
             print(f"[{self.agent_name}] Warning: Empty plan generated.")
             
        # Set run_retrosynthesis flag for downstream compatibility
        if "SynthesisAgent" in plan:
            task_params["run_retrosynthesis"] = True

        print(f"[{self.agent_name}] Generated Plan: {plan}")
        print(f"[{self.agent_name}] Reasoning: {reasoning}")
        
        # Log plan
        current_logs = state.get("task_params", {}).get("agent_logs", "")
        new_log = f"\n\n- **Coordinator Agent**:\n  - Reasoning: {reasoning}\n  - Plan: {plan}\n  - Resources: {current_resources}"
        task_params["agent_logs"] = current_logs + new_log
        
        return {
            "plan": plan,
            "plan_step": 0,
            "task_params": task_params,
            "results": {
                **state.get("results", {}),
                "coordinator": {"plan": plan, "reasoning": reasoning}
            }
        }


def coordinator_agent_node(state: AgentState) -> Dict[str, Any]:
    agent = CoordinatorAgent()
    return agent.run(state)
